name: Build & Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        include:
          - os: ubuntu-22.04
            toolset: gcc
            platform_version: 22.04
            arch: x86
          - os: macos-latest
            toolset: clang
            platform_version: 14
            arch: aarch64
          - os: windows-latest
            toolset: msvc
            platform_version: 2022
            arch: x86

    steps:
      - uses: actions/checkout@v4

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.85.0
          toolset: ${{ matrix.toolset }}
          platform_version: ${{ matrix.platform_version }}
          arch: ${{ matrix.arch }}

      - name: Configure
        shell: pwsh
        run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])"

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Install
        run: cmake --install build --config Release --prefix prefix

      - name: Test
        working-directory: build
        run: ctest --output-on-failure --no-tests=error -C Release -j 2
